name: pipeline

on:
  push:
    branches:
      - 'main'
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.set_version.outputs.safe_version }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Set application version
        id: set_version
        uses: kvendingoldo/semver-action@v1.8
        with:
          primary_branch: 'main'
      -
        name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: "ghcr.io"
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/kvendingoldo/azure_mi:${{ steps.set_version.outputs.safe_version }
      -
        name: Print image version
        run: echo ${{ steps.set_version.outputs.safe_version }}